image: "rustlang/rust:latest"

stages:
  - build
  - test

cache:
  paths:
    - target/

build:stable:
  stage: build
  script:
    - cargo +stable build --verbose
    - cargo +stable build --release --verbose

test:stable:
  stage: test
  dependencies:
    - build:stable
  script:
    - cargo +stable test --verbose
    - cargo +stable test --release --verbose

build:beta:
  stage: build
  script:
    - rustup toolchain add beta
    - cargo +beta build --verbose
    - cargo +beta build --release --verbose

test:beta:
  stage: test
  dependencies:
    - build:beta
  script:
    - rustup toolchain add beta
    - cargo +beta test --verbose
    - cargo +beta test --release --verbose

build:nightly:
  stage: build
  script:
    - rustup toolchain add nightly
    - cargo +nightly build --verbose
    - cargo +nightly build --release --verbose

test:nightly:
  stage: test
  dependencies:
    - build:nightly
  script:
    - rustup toolchain add nightly
    - cargo +nightly test --verbose
    - cargo +nightly test --release --verbose